<hr style="border-top: 1px dashed #03e; border-bottom: 1px solid #00e; color: #fff; background-color: #fff; height: 4px;"/>
<p>
欢迎关注微信公众号【<span style="border: 1px solid #4466ee; background-color:#feeafe; border-radius: 3px;">冰河杂谈</span>】（微信号:<font color=blue><b>icertalk</b></font>）<br />
坚持分享原创吐槽、观点及教程。也欢迎收到您的建议和互动。<br />
</p>
<img src="http://mmbiz.qpic.cn/mmbiz/zqHpggsS5RFyiasqJBqdyS2hVfGDeJ4Mibw5mRp4oBnpmchbXyN39PoianpJLAJhrfkLsjInZiaoAYXbqTwkNrZ1Xg/0" />
<p>
微博：weibo.com/wizicer<br />
微信：icerdesign<br />
网站：icerdesign.com<br />
Github：github.com/wizicer<br />
</p>
